---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
   name: http-01-production
   namespace: shopazany-prod-env
spec:
  acme:
    email: kasaliismail2@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-production-cluster-issuer
    solvers:
    - http01:
        ingress:
          ingressClassName: external-nginx
